# config.toml
# ===========
# Site configurations
#
baseURL = "https://mad0perator.github.io"
languageCode = 'en-us'

title = "mad0perator | link me"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "mad0perator"
  headline = "[.crypto]"
  image = "img/author.jpg"  # path relative to static directory

  links = [
    { email = "mailto:mad0perator.9216@cloak.id" },
    { link = "https://mad0perator.vercel.app/" },
    # { unstoppable = { href = "https://ud.me/mad0perator.crypto", text = "Unstoppable Domains profile" } },
    { github = "https://github.com/mad0perator" },
    { telegram = "https://t.me/mad0perator" },
    { twitter = "https://twitter.com/null_space" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
